FROM mysql:8.0.33-debian

COPY ./my.cnf /etc/mysql/conf.d/my.cnf

COPY ./develop/docker-entrypoint-override.sh /usr/local/bin/docker-entrypoint-override.sh

RUN chmod +x /usr/local/bin/docker-entrypoint-override.sh

ENTRYPOINT [ "/usr/local/bin/docker-entrypoint-override.sh" ]

CMD [ "mysqld" ]
