FROM nginx:1.25.1-bookworm

WORKDIR /work

COPY ./develop/default.conf /etc/nginx/conf.d/default.conf

COPY ./develop/docker-entrypoint-override.sh /usr/local/bin/docker-entrypoint-override.sh

RUN chmod +x /usr/local/bin/docker-entrypoint-override.sh

ENTRYPOINT [ "/usr/local/bin/docker-entrypoint-override.sh" ]

CMD [ "nginx", "-g", "daemon off;" ]
