FROM php:8.2.7-fpm-bookworm

WORKDIR /work/src/backend

RUN usermod -s /bin/bash www-data && \
    chown www-data:www-data /var/www && \
    apt-get update && \
    apt-get install -y --no-install-recommends locales vim git unzip && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    locale-gen ja_JP.UTF-8 && \
    localedef -f UTF-8 -i ja_JP ja_JP.UTF-8

RUN cp /usr/local/etc/php/php.ini-development /usr/local/etc/php/php.ini && \
    pecl install xdebug-3.2.1 && \
    docker-php-ext-enable xdebug && \
    docker-php-ext-install bcmath pdo_mysql

COPY --from=composer:2.5.8 /usr/bin/composer /usr/bin/composer
COPY ./php.ini /usr/local/etc/php/conf.d/php.ini
COPY ./xdebug.ini /usr/local/etc/php/conf.d/xdebug.ini

COPY ./docker-entrypoint-override.sh /usr/local/bin/docker-entrypoint-override.sh

RUN chmod +x /usr/local/bin/docker-entrypoint-override.sh

ENTRYPOINT [ "/usr/local/bin/docker-entrypoint-override.sh" ]

CMD [ "php-fpm" ]
